# Generated by Django 4.2.1 on 2023-07-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gmail',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
            ],
        ),
    ]
