# Generated by Django 4.2.1 on 2023-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0005_alter_gmail_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmail',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmail',
            name='tack_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gmail',
            name='task_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmail',
            name='task_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
