# Generated by Django 4.2.1 on 2023-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0006_gmail_balance_gmail_tack_info_gmail_task_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='時間餘額'),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='id',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='tack_info',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='任務內容'),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='task_cost',
            field=models.IntegerField(default=0, verbose_name='任務時長'),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='task_name',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='任務名稱'),
        ),
    ]
