# Generated by Django 4.2.1 on 2023-08-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0007_alter_gmail_balance_alter_gmail_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gmail',
            new_name='trade_request',
        ),
    ]
