# Generated by Django 4.2.1 on 2023-08-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0011_alter_trade_request_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade_request',
            old_name='tack_info',
            new_name='task_info',
        ),
    ]
