# Generated by Django 4.2.1 on 2023-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0012_rename_tack_info_trade_request_task_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_info',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False, verbose_name='email')),
                ('balance', models.IntegerField(default=0, verbose_name='時間餘額')),
            ],
        ),
    ]
