# Generated by Django 4.2.1 on 2023-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0013_id_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='時間餘額'),
        ),
    ]
