# Generated by Django 4.2.1 on 2023-09-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0014_alter_trade_request_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='id',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
