# Generated by Django 4.2.1 on 2023-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0015_alter_trade_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='時間餘額'),
        ),
    ]
