# Generated by Django 4.2.1 on 2023-09-27 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0016_alter_trade_request_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='people_limit',
            field=models.IntegerField(default=0, verbose_name='人數限制'),
        ),
        migrations.AddField(
            model_name='trade_request',
            name='point_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='積分限制'),
        ),
    ]
