# Generated by Django 4.2.5 on 2023-10-04 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0019_profile_delete_id_info_delete_trade_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_info',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False, verbose_name='email')),
                ('balance', models.IntegerField(default=0, verbose_name='時間餘額')),
            ],
        ),
        migrations.CreateModel(
            name='trade_request',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('balance', models.IntegerField(default=0, verbose_name='時間餘額')),
                ('task_name', models.CharField(default=None, max_length=30, null=True, verbose_name='任務名稱')),
                ('task_cost', models.IntegerField(default=0, verbose_name='任務時長')),
                ('now_people', models.IntegerField(default=0, verbose_name='現在人數')),
                ('max_people', models.IntegerField(default=0, verbose_name='總人數')),
                ('point_limit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='積分限制')),
                ('description_limit', models.TextField(blank=True, default=None, null=True, verbose_name='專長限制')),
                ('task_info', models.TextField(blank=True, default=None, null=True, verbose_name='任務內容')),
                ('thumbnail', models.TextField(blank=True, verbose_name='圖片路徑')),
                ('result', models.CharField(choices=[('None', ' '), ('True', '通過'), ('False', '不通過')], default=None, max_length=10000, null=True, verbose_name='解果')),
            ],
        ),
    ]
