# Generated by Django 4.2.5 on 2023-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0020_id_info_trade_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='id_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='時間餘額'),
        ),
    ]
