# Generated by Django 4.2.5 on 2023-10-18 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_gmail', '0021_delete_id_info_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='trust_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_point', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='信用積分')),
                ('decrease_point', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='扣除積分')),
                ('obj_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
