# Generated by Django 4.2.5 on 2023-10-18 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0022_trust_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust_point',
            name='increase_point',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='增加積分'),
        ),
    ]
