# Generated by Django 4.2.5 on 2023-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0023_trust_point_increase_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='id',
            field=models.EmailField(max_length=10000, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
