# Generated by Django 4.2.5 on 2023-10-25 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0025_rename_id_trade_request_obj_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust_point',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='信用積分'),
        ),
    ]
