# Generated by Django 4.2.5 on 2023-10-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0026_profile_trust_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trust_point',
            name='trust_point',
        ),
    ]
