# Generated by Django 4.2.5 on 2023-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0027_remove_trust_point_trust_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='img',
            field=models.TextField(blank=True, verbose_name='圖片檔案'),
        ),
    ]
