# Generated by Django 4.2.5 on 2023-11-30 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0028_trade_request_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='request_type',
            field=models.IntegerField(choices=[('0', '預設'), ('1', '特殊')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trade_request',
            name='point_limit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='積分限制'),
        ),
    ]
