# Generated by Django 4.2.5 on 2023-11-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0029_trade_request_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='request_type',
            field=models.IntegerField(choices=[('0', '預設'), ('1', '特殊')], default=0),
        ),
    ]
