# Generated by Django 4.2.5 on 2023-11-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0031_alter_trade_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_request',
            name='request_type',
            field=models.CharField(choices=[('True', '預設'), ('False', '特殊')], default=None, max_length=10000, null=True, verbose_name='交易類型'),
        ),
    ]
