# Generated by Django 4.2.5 on 2023-11-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0032_alter_trade_request_request_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade_request',
            old_name='request_type',
            new_name='requests_type',
        ),
    ]
