# Generated by Django 4.2.5 on 2023-11-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0033_rename_request_type_trade_request_requests_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade_request',
            name='requests_type',
        ),
    ]
