# Generated by Django 4.2.5 on 2023-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0034_remove_trade_request_requests_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_task',
            field=models.IntegerField(default=0, verbose_name='已發布任務數量'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_task_max',
            field=models.IntegerField(default=5, verbose_name='發布任務數量上限'),
        ),
    ]
