# Generated by Django 4.2.5 on 2023-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0035_profile_number_of_task_profile_number_of_task_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade_request',
            name='obj_user',
            field=models.EmailField(max_length=10000, verbose_name='email'),
        ),
    ]
