# Generated by Django 4.2.1 on 2023-09-13 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust_point',
            name='trust_point',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='信用積分'),
        ),
    ]
