# Generated by Django 4.2.1 on 2023-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0002_alter_trust_point_trust_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='專長'),
        ),
    ]
