# Generated by Django 4.2.1 on 2023-09-20 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0003_matchmaking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust_point',
            name='increase_point',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='扣除積分'),
        ),
    ]
