# Generated by Django 4.2.1 on 2023-09-20 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0004_trust_point_increase_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='decrease_point',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False, verbose_name='email')),
                ('decrease_point', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='扣除積分')),
            ],
        ),
        migrations.RemoveField(
            model_name='trust_point',
            name='increase_point',
        ),
    ]
