# Generated by Django 4.2.1 on 2023-09-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0005_decrease_point_remove_trust_point_increase_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='decrease_point',
            new_name='decreasepoint',
        ),
    ]
