# Generated by Django 4.2.1 on 2023-09-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust_point', '0006_rename_decrease_point_decreasepoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='decreasepoint',
            new_name='decrease_point',
        ),
    ]
